apiVersion: v1
kind: Service
metadata:
    name: "kctal-9390"
    labels:
        app: "kctal-9390"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "kctal-9390"