on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: crtal.azurecr.io
        username: ${{ secrets.acr_crtal_username }}
        password: ${{ secrets.acr_crtal_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t crtal.azurecr.io/kctal:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push crtal.azurecr.io/kctal:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_kctal_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep kc-tal9f5f | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace kc-tal9f5f`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: kc-tal9f5f
        container-registry-url: crtal.azurecr.io
        container-registry-username: ${{ secrets.acr_crtal_username }}
        container-registry-password: ${{ secrets.acr_crtal_password }}
        secret-name: kctaldockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: kc-tal9f5f
        manifests: |
          manifests/deployment-7.yml
          manifests/service-7.yml
        images: |
          crtal.azurecr.io/kctal:${{ github.sha }}
        imagepullsecrets: |
          kctaldockerauth
